Edit utils.py and main.py
Error message:

```
C:\Users\ryuth\AppData\Roaming\Python\Python311\site-packages\transformers\models\segformer\feature_extraction_segformer.py:28: FutureWarning: The class SegformerFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use SegformerImageProcessor instead.
  warnings.warn(
INFO:     127.0.0.1:57068 - "POST /predict/image HTTP/1.1" 500 Internal Server Error  
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\fastapi\applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Python311\Lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Python311\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\Python311\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)  
  File "C:\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Python311\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender) 
  File "C:\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "C:\Python311\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)   
  File "C:\Python311\Lib\site-packages\starlette\routing.py", line 718, in __call__   
    await route.handle(scope, receive, send)
  File "C:\Python311\Lib\site-packages\starlette\routing.py", line 276, in handle     
    await self.app(scope, receive, send)   
  File "C:\Python311\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\fastapi\routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "C:\Users\ryuth\OneDrive\Desktop\ArterySegmentation_Web\upload_fastapi\artery-segmentation\src\api\main.py", line 20, in prediction_api
    output = segment(image)
             ^^^^^^^^^^^^^^
  File "C:\Users\ryuth\OneDrive\Desktop\ArterySegmentation_Web\upload_fastapi\artery-segmentation\src\api\models\segformer\core.py", line 52, in segment
    size=image.size[::-1], # (height, width)
         ~~~~~~~~~~^^^^^^
TypeError: 'int' object is not subscriptable
```